http://localhost:5000/

### 

POST http://localhost:5000/join-room/10 HTTP/1.1
Content-Type: application/json

{
    "peerId": "user01"
}

###
GET http://localhost:5000/members/10 HTTP/1.1

###
POST http://localhost:5000/leave-room/10 HTTP/1.1
Content-Type: application/json

{
    "peerId": "user01"
}

###

GET http://localhost:5000/peerjs/app/ps/peers